use crate::model::{AppInfo, ScanResult, Source};
use std::path::PathBuf;

pub fn demo_result() -> ScanResult {
    ScanResult {
        apps: demo_apps(),
        errors: vec![],
    }
}

fn demo_apps() -> Vec<AppInfo> {
    let outdated = vec![
        AppInfo {
            name: "1Password".into(),
            bundle_id: "com.1password.1password".into(),
            installed_version: "8.10.28".into(),
            latest_version: Some("8.10.56".into()),
            source: Source::Sparkle,
            has_update: true,
            changelog: Some("Performance improvements and bug fixes.".into()),
            app_path: PathBuf::from("/Applications/1Password.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Discord".into(),
            bundle_id: "com.hnc.Discord".into(),
            installed_version: "0.0.309".into(),
            latest_version: Some("0.0.315".into()),
            source: Source::Homebrew,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Discord.app"),
            cask_token: Some("discord".into()),
        },
        AppInfo {
            name: "Figma".into(),
            bundle_id: "com.figma.Desktop".into(),
            installed_version: "124.1.6".into(),
            latest_version: Some("124.5.2".into()),
            source: Source::Homebrew,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Figma.app"),
            cask_token: Some("figma".into()),
        },
        AppInfo {
            name: "Firefox".into(),
            bundle_id: "org.mozilla.firefox".into(),
            installed_version: "124.0.2".into(),
            latest_version: Some("131.0".into()),
            source: Source::Homebrew,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Firefox.app"),
            cask_token: Some("firefox".into()),
        },
        AppInfo {
            name: "iTerm2".into(),
            bundle_id: "com.googlecode.iterm2".into(),
            installed_version: "3.5.4".into(),
            latest_version: Some("3.5.10".into()),
            source: Source::Sparkle,
            has_update: true,
            changelog: Some("Bug fixes and stability improvements.".into()),
            app_path: PathBuf::from("/Applications/iTerm.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Keynote".into(),
            bundle_id: "com.apple.iWork.Keynote".into(),
            installed_version: "14.1".into(),
            latest_version: Some("14.3".into()),
            source: Source::AppStore,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Keynote.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Notion".into(),
            bundle_id: "notion.id".into(),
            installed_version: "3.11.0".into(),
            latest_version: Some("4.2.0".into()),
            source: Source::Homebrew,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Notion.app"),
            cask_token: Some("notion".into()),
        },
        AppInfo {
            name: "Pages".into(),
            bundle_id: "com.apple.iWork.Pages".into(),
            installed_version: "14.1".into(),
            latest_version: Some("14.3".into()),
            source: Source::AppStore,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Pages.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Raycast".into(),
            bundle_id: "com.raycast.macos".into(),
            installed_version: "1.74.1".into(),
            latest_version: Some("1.82.5".into()),
            source: Source::Homebrew,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Raycast.app"),
            cask_token: Some("raycast".into()),
        },
        AppInfo {
            name: "Slack".into(),
            bundle_id: "com.tinyspeck.slackmacgap".into(),
            installed_version: "4.38.125".into(),
            latest_version: Some("4.41.30".into()),
            source: Source::AppStore,
            has_update: true,
            changelog: None,
            app_path: PathBuf::from("/Applications/Slack.app"),
            cask_token: None,
        },
    ];

    let up_to_date = vec![
        AppInfo {
            name: "Arc".into(),
            bundle_id: "company.thebrowser.Browser".into(),
            installed_version: "1.73.0".into(),
            latest_version: Some("1.73.0".into()),
            source: Source::Homebrew,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Arc.app"),
            cask_token: Some("arc".into()),
        },
        AppInfo {
            name: "Bear".into(),
            bundle_id: "net.shinyfrog.bear".into(),
            installed_version: "2.3.5".into(),
            latest_version: Some("2.3.5".into()),
            source: Source::AppStore,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Bear.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Safari".into(),
            bundle_id: "com.apple.Safari".into(),
            installed_version: "18.3".into(),
            latest_version: Some("18.3".into()),
            source: Source::AppStore,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Safari.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Spotify".into(),
            bundle_id: "com.spotify.client".into(),
            installed_version: "1.2.50".into(),
            latest_version: Some("1.2.50".into()),
            source: Source::Homebrew,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Spotify.app"),
            cask_token: Some("spotify".into()),
        },
        AppInfo {
            name: "Sublime Text".into(),
            bundle_id: "com.sublimetext.4".into(),
            installed_version: "4.0.4180".into(),
            latest_version: Some("4.0.4180".into()),
            source: Source::Sparkle,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Sublime Text.app"),
            cask_token: None,
        },
        AppInfo {
            name: "TablePlus".into(),
            bundle_id: "com.tinyapp.TablePlus".into(),
            installed_version: "6.2.2".into(),
            latest_version: Some("6.2.2".into()),
            source: Source::Homebrew,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/TablePlus.app"),
            cask_token: Some("tableplus".into()),
        },
        AppInfo {
            name: "Things 3".into(),
            bundle_id: "com.culturedcode.ThingsMac".into(),
            installed_version: "3.20.9".into(),
            latest_version: Some("3.20.9".into()),
            source: Source::AppStore,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Things3.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Transmit".into(),
            bundle_id: "com.panic.Transmit".into(),
            installed_version: "5.10.4".into(),
            latest_version: Some("5.10.4".into()),
            source: Source::Sparkle,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Transmit 5.app"),
            cask_token: None,
        },
        AppInfo {
            name: "Visual Studio Code".into(),
            bundle_id: "com.microsoft.VSCode".into(),
            installed_version: "1.96.2".into(),
            latest_version: Some("1.96.2".into()),
            source: Source::Homebrew,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Visual Studio Code.app"),
            cask_token: Some("visual-studio-code".into()),
        },
        AppInfo {
            name: "Xcode".into(),
            bundle_id: "com.apple.dt.Xcode".into(),
            installed_version: "16.2".into(),
            latest_version: Some("16.2".into()),
            source: Source::AppStore,
            has_update: false,
            changelog: None,
            app_path: PathBuf::from("/Applications/Xcode.app"),
            cask_token: None,
        },
    ];

    let mut apps = outdated;
    apps.extend(up_to_date);
    apps
}
